version: '3.8'
services:
  db-transaksiq:
    image: postgres:16
    ports:
      - "5437:5432"
    environment:
      - POSTGRES_DB=transaksiku_db
      - POSTGRES_USER=transaksiq_user
      - POSTGRES_PASSWORD=passwordtransaksi12345
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
